### ISSUE TITLE
nav_msgs::Odometry can't use

### ISSUE THREAD

**Issue by quaei676** [ROBOTIS-GIT/ros2arduino#18]
I can use Pose or PoseWithCovariance to transfer the data.
But I dont't know why I can't use the nav_msgs::Odometry.
ros2arduino version:0.0.9
OpenCR version: 1.4.5
Many thanks.

**Comment by OpusK** [comment]
I also saw this issue. We have found that data is not being transmitted after the writer is created.
In this regard, we will debug and answer your questions.

**Comment by OpusK** [comment]
Hi, @quaei676

As Micro-XRCE-DDS has been updated, this issue seems to be resolved.
This update is currently applied to ros2arduino 0.1.1.

However, the following issues still exist and it is difficult to receive normal data.
If the issue below is resolved, the Odometry message seems to be available normally.

 - [Micro-XRCE-DDS-Agent#99](https://github.com/eProsima/Micro-XRCE-DDS-Agent/issues/99)

**Comment by quaei676** [comment]
Hi, @OpusK 

Thanks for answering my questions. 
I will look forward to next version.
Many thanks.

**Comment by OpusK** [comment]
@quaei676 

This issue is fixed in version [0.1.2](https://github.com/ROBOTIS-GIT/ros2arduino/releases/tag/0.1.2).
Please try after the update.

**Comment by quaei676** [comment]
@OpusK 

My robot needs imu data.
Therefore, I directly use sensors.imu_.rpy[].
However, I find that I have to subscribe imu data, 
then sensors.imu_.rpy[] have normal data. 
It should be no problem in ros2arduino version:0.0.9.
Many thanks.
